### ISSUE TITLE
Program won't run?

### ISSUE THREAD

**Issue by FluffyTrooper2001** [ifly6/Communique#9]
Hi, sorry to bother you, and I don't know if this is the right place for this, but when I run the program with Java runtime environment installed, it runs for about 2 seconds according to task manager, then stops. It was working fine yesterday, but I didn't change anything, so I have no idea what could have happened.
(Communique_8.2.jar)

**Comment by ifly6** [comment]
Can you provide a log? It should be located in your Application support folder

**Comment by FluffyTrooper2001** [comment]
I have searched my folder system, I cannot find either.
I am using Windows 10, is there any way you could specify where to find these logs?

**Comment by ifly6** [comment]
Re this issue. I think that the problem probably was associated with Communique attempting to save or load a file with colons in it on Windows systems. I myself ran entirely on Mac and Linux, which may have been an issue.

Absent further logs, I'll close the issue.

N.b. future reference: logs can be found on Windows at `%APPDATA%`.
